name: qpsolvers_doc
channels:
    - conda-forge
dependencies:
    - clarabel
    - cvxopt
    - daqp
    - jaxopt
    - kvxopt
    - pip >= 21.3.1
    - proxsuite
    - python=3.10
    - qpsolvers
    - quadprog
    - pip:
        - furo >= 2023.8.17
        - highspy >= 1.5.3
        - piqp >= 0.2.2
        - qpalm >= 1.2.1
        - qpax >= 0.0.6
        - sip-python >= 0.0.2
        - sphinx >= 7.2.2
        - sphinx-autodoc-typehints
        - sphinx-mathjax-offline
