name: Documentation

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    workflow_dispatch:

defaults:
    run:
        # See https://github.com/mamba-org/provision-with-micromamba#important
        shell: bash -l {0}

jobs:
    docs:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: "Checkout Git repository"
              uses: actions/checkout@v3

            - name: "Install Conda environment with Micromamba"
              uses: mamba-org/provision-with-micromamba@main
              with:
                  cache-downloads: true
                  cache-env: true
                  environment-file: doc/environment.yml
                  environment-name: qpsolvers

            - name: "Checkout qpSWIFT"
              uses: actions/checkout@v3
              with:
                  repository: qpSWIFT/qpSWIFT
                  path: qpSWIFT

            - name: "Install qpSWIFT"
              run: |
                  cd qpSWIFT/python
                  python setup.py install

            - name: "Build documentation"
              run: |
                  sphinx-build doc _build -W

            - name: "Deploy to GitHub Pages"
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
              with:
                  publish_branch: gh-pages
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: _build/
                  force_orphan: true
